In [ ]:
from tensorflow.keras.models import load_model, Model
from tensorflow.keras.utils import plot_model
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.models import Sequential, load_model, Model
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, Input, MaxPooling2D, Concatenate, AveragePooling1D, Reshape, Activation, add, Conv2DTranspose, BatchNormalization, UpSampling2D, SeparableConv2D
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.utils import plot_model, Sequence
from tensorflow.keras.losses import CategoricalCrossentropy, Reduction, BinaryCrossentropy
from tensorflow.keras.layers import Lambda
from tensorflow.keras.activations import softmax
from tensorflow import roll, norm, keras
import tensorflow as tf
import tensorflow.keras.backend as K
import tensorflow.keras.applications as A

import tensorflow as tf
import numpy as np

In [15]:
base_model = A.MobileNetV2(include_top=False, weights="imagenet")

model = Model(inputs=base_model.inputs, outputs=base_model.output)
optimizer = Adam(lr=3e-4)
model.compile(loss='categorical_crossentropy', optimizer=optimizer)

9420800/9406464 [==============================] - 0s 0us/step


In [16]:
print(model.summary())

Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_6 (InputLayer)            [(None, None, None,  0                                            
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, None, None, 3 864         input_6[0][0]                    
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, None, None, 3 128         Conv1[0][0]                      
__________________________________________________________________________________________________
Conv1_relu (ReLU)               (None, None, None, 3 0           bn_Conv1[0][0]                   
____________________________________________________________________________________________

In [17]:
model.save('test.h5')

/opt/conda/lib/python3.9/site-packages/keras/utils/generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '


In [ ]:
%load_ext autoreload
%autoreload 2

from include import loss

In [36]:
y_true = [[0.0, 1.0], [0.0, 0.0], [1.0,0.0]]
y_pred = [[0.1, 0.95], [0.1, 0.0], [0.8, 0.05]]

loss.weighted_ce(y_true, y_pred)

tf.Tensor(
[[-0.         -0.         -0.22313102]
 [-0.1538483  -0.         -0.        ]], shape=(2, 3), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=0.37697932>

In [10]:
we = K.constant(np.array([[2.07], [1.36], [0.67], [0.54], [0.08], [0.09], [100]])) 
we /= K.sum(we)
we = 1 / we
we /= K.sum(we)
print(we)

tf.Tensor(
[[1.7140711e-02]
 [2.6089169e-02]
 [5.2957118e-02]
 [6.5706052e-02]
 [4.4351587e-01]
 [3.9423630e-01]
 [3.5481271e-04]], shape=(7, 1), dtype=float32)
